### ISSUE TITLE
Get the top definition.

### ISSUE THREAD

**Issue by sasalx** [mvrilo/urban#12]
From what I can see API of Urban Dic. puts the definition with most thumbs up first. Many times this cause a bad selection of definition. Is there a way to take the definition with highest(thumbs_up - thumbs_down) ?

Example:
http://api.urbandictionary.com/v0/define?term=hs

**Comment by Corewave** [comment]
How to see if the word exists or not, because if i enter a word that doesn't exist it errors and stops by bot.
