### ISSUE TITLE
the API url that getData forms no longer seems to work

### ISSUE THREAD

**Issue by FranciscoG** [mvrilo/urban#13]
When I do this:

```
var urban = require('urban'),
    catfish = urban('catfish');

catfish.first(function(json) {
    console.log(json);
});

```
Dictionary.fn.getData @ https://github.com/mvrilo/urban/blob/master/lib/urban.js#L66

The above script will create a URL for the GET request and it doesn't work anymore
http://api.urbandictionary.com/v0/define?page=undefined&term=catfish

### However
if you remove `page=undefined` though,  it works
http://api.urbandictionary.com/v0/define?term=catfish

Is anyone else experiencing this?  this lib just completely stopped working for me recently and it's just for this small reason.

**Comment by generalwrex** [comment]
Thank you @FranciscoG, it allowed me to fix a discord bot ;)  Did the same thing, I removed &page=

![d2d944c7dca1cd8ae282dcdb0d628726](https://user-images.githubusercontent.com/1731139/43292905-67bfb048-90ec-11e8-821f-8758beef9e5e.png)

**Comment by gt-c** [comment]
This happened to me too, I decided I'm not going to deal with this out of date unpromisified library, so I switched to [another urban dictionary lib](https://www.npmjs.com/package/urban-dictionary) which I have found much better.

**Comment by FranciscoG** [comment]
yeah i completely removed it and I'm just hitting the api myself

https://github.com/FranciscoG/DerpyBot/blob/master/bot/commands/fun/urban.js
